export const DataObjOne = {
  id: "first",
  lightBg: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "Sobre Nosotros",
  headLine: "TITULO DE LA SECCION",
  description:
    "Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500",
  buttomLabel: "Comienza Aqui",
  bgimg: true,
  imgStart: false,
  img: require("../../images/imgpdc.jpg"),
  alt: "...",
  dark: true,
  primary: true,
  darkText: true,
};
export const DataObjtwo = {
  id: "first",
  lightBg: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "Texto Alternativo",
  headLine: "TITULO DE LA SECCION",
  description:
    "Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500",
  buttomLabel: "Comienza Aqui",
  imgStart: false,
  img: require("../../images/imgpdc.jpg"),
  alt: "...",
  dark: true,
  primary: true,
  darkText: true,
};
export const DataObjthree = {
  id: "first",
  lightBg: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "Texto Alternativo",
  headLine: "TITULO DE LA SECCION",
  description:
    "Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto. Lorem Ipsum ha sido el texto de relleno estándar de las industrias desde el año 1500",
  buttomLabel: "Comienza Aqui",
  imgStart: false,
  img: require("../../images/imgpdc.jpg"),
  alt: "...",
  dark: true,
  primary: true,
  darkText: true,
};
